// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'item-info-row-example-label'
  | 'item-section-example1-head-text'
  | 'item-section-example1-sidenav-tooltip'
  | 'item-section-example2-button-tooltip'
  | 'item-section-example2-head-text'
  | 'item-section-example2-sidenav-tooltip'
  | 'menuitem-filemenulabel'
  | 'openreview-pref-api-base-url'
  | 'openreview-pref-enable'
  | 'openreview-pref-help'
  | 'openreview-pref-include-statistics'
  | 'openreview-pref-input'
  | 'openreview-pref-invalid-number'
  | 'openreview-pref-invalid-url'
  | 'openreview-pref-max-retries'
  | 'openreview-pref-request-timeout'
  | 'openreview-pref-reset-defaults'
  | 'openreview-pref-save-mode'
  | 'openreview-pref-save-mode-html'
  | 'openreview-pref-save-mode-markdown'
  | 'openreview-pref-settings-saved'
  | 'openreview-pref-title'
  | 'prefs-table-detail'
  | 'prefs-table-title'
  | 'prefs-title'
  | 'startup-begin'
  | 'startup-finish'
  | 'tabpanel-lib-tab-label'
  | 'tabpanel-reader-tab-label';
